apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersvc-deployment
  labels:
    app: usersvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersvc
  template:
    metadata:
      labels:
        app: usersvc
    spec:
      containers:
      - name: usersvc
        image: localhost:5000/usersvc:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: usersvc-service
spec:
  selector:
    app: usersvc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: usersvc-configmap
data:
  svc_url: usersvc-service