apiVersion: apps/v1
kind: Deployment
metadata:
  name: listingsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listingsvc
  template:
    metadata:
      labels:
        app: listingsvc
    spec:
      containers:
      - name: listingsvc
        image: localhost:5000/listingsvc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080